### ISSUE TITLE
How can i connect MatrikonOPC Server for Simulation

### ISSUE THREAD

**Issue by jiasondouble** [FreeOpcUa/python-opcua#18] opened 2015-07-28 11:09 UTC
Hello. thank you for python-opcua
MatrikonOPC Server for Simulation is Run in windows2003
python-opc is client that Run in linux
the windows2003 ip is 192.168.1.110. MatrikonOPC Server for Simulation Server Name is Matrikon.OPC.Simulation.1  and the windows2003 user is OPCTest password OPC

I'm using Code in example-client.py

if __name__ == "__main__":
    logging.basicConfig(level=logging.WARN)
    #logger = logging.getLogger("KeepAlive")
    #logger.setLevel(logging.DEBUG)

    client = Client("opc.tcp://OPCTest@192.168.1.110:135/Matrikon.OPC.Simulation.1")
    #client = Client("opc.tcp://localhost:4841/freeopcua/server/")
    # client = Client("opc.tcp://admin@localhost:4841/freeopcua/server/") #connect using a user

    try:
        client.connect()

but connect fail ,how can I to do

**Comment by oroulet** [comment] 2015-07-28 16:30
I have never tested pasword. but try to specify it in url. It is supposed
to be implemented...
http://www.cs.rutgers.edu/~watrous/user-pass-url.html

Does it work if logging as anonymous ( and enabling it in server) ?

**Comment by jiasondouble** [comment] 2015-07-29 02:49
thank you 
i try to use the code that  client = Client("opc.tcp://OPCTest:OPC@192.168.1.110:135/Matrikon.OPC.Simulation.1")
that also can't connect
when I run the exampl_client.py that always no reply, I don't know why.
Function “def send_hello(self, url)" in binary_client.py file 
I print the  self._lock and  future.result() .the self._lock have value is <thread.lock object at 0x1fbff030>.but future.result() is  no reply
![eee](https://cloud.githubusercontent.com/assets/9522091/8948934/733889d8-35df-11e5-978d-75c2644e563c.png)

I'm sorry my English is not good, I am from China. I hope I said above understand

**Comment by jiasondouble** [comment] 2015-07-29 08:56
another question , can  the opcua connect that MatrikonOPC ?

**Comment by oroulet** [comment] 2015-07-29 08:59
Yes I tested this server a few month ago but only using anonymous.
But I do not have access to such a server before a few weeks so I cannot
test for you.

**Comment by oroulet** [comment] 2015-10-07 15:12
duplicate of https://github.com/FreeOpcUa/python-opcua/issues/23

**Closed** 2016-01-13 19:39 UTC
Labels: duplicate

**Comment by cscortes** [comment] 2017-08-17 20:24
I guess I am having all kinds of badness trying to connect to Matrikon's simulation server.  I thought it would be a no brainer.   I don't think that I have it set to authentication.  How would I know?

I am using:
import opcua

c = opcua.Client("opc.tpc://localhost:135/Matrikon.OPC.Simulation.1")
c.connect()

seems simple enough, but just wont do it.  I do have Matrikons OPC explorer.  And I do see the simulation stuff fine.  I turned off the firewall just in case, I am running out of ideas.  

Ultimately I wanted to connect to Matrikon's Desktop Historian and pull items from a specific time -- is that possible with freeopcua??

**Comment by zerox1212** [comment] 2017-08-18 00:02
Can you connect to your server with UA Expert?

**Comment by oroulet** [comment] 2017-08-18 05:13
@cscortes yes this should work fine. As @zerox1212 wrote, try with uaexpert . You can also call get_endpoints() before connecting to see what endpoints are available.
